version: 0.2

# https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-cd-pipeline.html
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - env
      - aws --version
      - aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin 058264274806.dkr.ecr.ap-southeast-2.amazonaws.com
      - IMAGE_TAG=$(echo release-$CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-10)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 
        058264274806.dkr.ecr.ap-southeast-2.amazonaws.com/aws-ecr:latest
      - echo Writing image definitions file...
      - printf '[{"name":"aws-ecr","imageUri":"058264274806.dkr.ecr.ap-southeast-2.amazonaws.com/aws-ecr:latest"}]' > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files: imagedefinitions.json
